package:
  name: branca
  version: 0.8.2
  top-level:
    - branca
source:
  url: https://files.pythonhosted.org/packages/7e/50/fc9680058e63161f2f63165b84c957a0df1415431104c408e8104a3a18ef/branca-0.8.2-py3-none-any.whl
  sha256: 2ebaef3983e3312733c1ae2b793b0a8ba3e1c4edeb7598e10328505280cf2f7c
requirements:
  run:
    - jinja2
about:
  home: https://github.com/python-visualization/branca
  PyPI: https://pypi.org/project/branca
  summary: Generate complex HTML+JS pages with Python
  license: MIT
