package:
  name: tifffile
  version: 2025.10.16
  top-level:
    - tifffile
source:
  url: https://files.pythonhosted.org/packages/e6/5e/56c751afab61336cf0e7aa671b134255a30f15f59cd9e04f59c598a37ff5/tifffile-2025.10.16-py3-none-any.whl
  sha256: 41463d979c1c262b0a5cdef2a7f95f0388a072ad82d899458b154a48609d759c
requirements:
  run:
    - numpy
about:
  home: https://www.cgohlke.com
  PyPI: https://pypi.org/project/tifffile
  summary: Read and write TIFF files
  license: BSD-3-Clause
